dbt:
  outputs:
    default:
      account: account
      user: user
      password: password
      warehouse: jaffle_shop_wh
      role: dbt_role
      database: jaffle_shop_db
      schema: default_schema
      type: snowflake
      threads: 1

  target: default
